// <auto-generated>
// Auto-generated by StoneAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api.Files
{
    using sys = System;
    using col = System.Collections.Generic;
    using re = System.Text.RegularExpressions;

    /// <summary>
    /// <para>Indicates that there used to be a file or folder at this path, but it no longer
    /// exists.</para>
    /// </summary>
    /// <seealso cref="Global::Dropbox.Api.Files.Metadata" />
    public class DeletedMetadata : Metadata
    {
        /// <summary>
        /// <para>Initializes a new instance of the <see cref="DeletedMetadata" />
        /// class.</para>
        /// </summary>
        /// <param name="name">The last component of the path (including extension). This never
        /// contains a slash.</param>
        /// <param name="pathLower">The lowercased full path in the user's Dropbox. This always
        /// starts with a slash. This field will be null if the file or folder is not
        /// mounted.</param>
        /// <param name="pathDisplay">The cased path to be used for display purposes only. In
        /// rare instances the casing will not correctly match the user's filesystem, but this
        /// behavior will match the path provided in the Core API v1, and at least the last
        /// path component will have the correct casing. Changes to only the casing of paths
        /// won't be returned by <see
        /// cref="Dropbox.Api.Files.Routes.FilesUserRoutes.ListFolderContinueAsync" />. This
        /// field will be null if the file or folder is not mounted.</param>
        /// <param name="parentSharedFolderId">Deprecated. Please use <see
        /// cref="Dropbox.Api.Files.FileSharingInfo.ParentSharedFolderId" /> or <see
        /// cref="Dropbox.Api.Files.FolderSharingInfo.ParentSharedFolderId" /> instead.</param>
        public DeletedMetadata(string name,
                               string pathLower = null,
                               string pathDisplay = null,
                               string parentSharedFolderId = null)
            : base(name, pathLower, pathDisplay, parentSharedFolderId)
        {
        }

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="DeletedMetadata" />
        /// class.</para>
        /// </summary>
        /// <remarks>This is to construct an instance of the object when
        /// deserializing.</remarks>
        [sys.ComponentModel.EditorBrowsable(sys.ComponentModel.EditorBrowsableState.Never)]
        public DeletedMetadata()
        {
        }
    }
}
